### ISSUE TITLE
[bug] String.split is missing from mooncontroller's enviroment

### ISSUE THREAD

**Issue by TheEt1234** [mt-mods/mooncontroller#5]
The recently added string.split to normal luacontrollers is missing from the mooncontroller enviroment

**Comment by OgelGames** [comment]
It was added in https://github.com/mt-mods/mooncontroller/commit/85a0959df01c930b6cfe8dd18d658d90af6ab695, and I just checked in-game and it's still there and working fine.

**Comment by TheEt1234** [comment]
oh right i am a dumbo
